FROM python:3.12-slim
ARG MINA_VERSION=development
WORKDIR /opt/mina/administrator
COPY administrator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY administrator .
EXPOSE 9080
ENV MINA_ADMIN_DATA_DIR=/var/lib/mina/administrator
ENV MINA_ADMIN_VERSION=${MINA_VERSION}
CMD ["python", "run_admin.py"]
