import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';

const source=await readFile(new URL('../src/ActivityEditor.tsx',import.meta.url),'utf8');
const ast=ts.createSourceFile('editor.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const compile=text=>ts.transpileModule(text,{compilerOptions:{jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022}}).outputText;
function all(node) {return node && typeof node==='object' ? [node,...(node.children||[]).flatMap(all)] : [];}

test('selected project schema renders only its selector; inline schema remains editable',()=>{
  const fn=ast.statements.find(s=>s.name?.text==='TransformSchemaEditor');
  const context=vm.createContext({React:{createElement:(type,props,...children)=>({type,props,children:children.flat(Infinity)})},Braces:'icon',SchemaHierarchyPreview:'preview'});
  vm.runInContext(compile(fn.getText(ast)),context);
  const render=config=>context.TransformSchemaEditor({config,schemas:[{id:'schema',name:'Order.xsd',content:'<schema/>'}],setConfig() {}});
  const selected=all(render({targetSchemaId:'schema',targetSchemaText:'<schema/>'}));
  assert.equal(selected.filter(n=>n.type==='textarea'||n.type==='preview').length,0);
  assert.equal(selected.find(n=>n.type==='select').props.value,'schema');
  assert.equal(all(render({targetSchemaText:'<schema/>'})).find(n=>n.type==='textarea').props.value,'<schema/>');
});

test('duplicating a mapped repeating structure creates an independent empty occurrence',()=>{
  let declaration;
  function visit(node) {if(ts.isVariableDeclaration(node)&&node.name.getText(ast)==='duplicateOccurrence') declaration=node;ts.forEachChild(node,visit);}
  visit(ast);
  for(const operator of ['for-each','for-each-group']) {
    const parent={target:'Record',operator,source:'${input.rows}',select:'${input.rows}',groupBy:'name',functions:['trim'],constant:'old',condition:'true'};
    const child={target:'Record.Name',source:'${input.rows.Name}',autoGenerated:true};
    let result;
    const context=vm.createContext({mappings:[parent,child],crypto:{randomUUID:()=> 'new-copy'},setMappings:v=>result=v});
    vm.runInContext(compile(`const ${declaration.getText(ast)}; duplicateOccurrence('Record');`),context);
    assert.equal(result.length,3);
    assert.equal(result[0],parent);assert.equal(result[1],child);
    const copy=result[2];assert.equal(copy.source,'');assert.equal(copy.operator,operator);
    assert.equal(copy.occurrenceId,'occurrence-new-copy');assert.equal(copy.duplicateOf,'primary');
    for(const key of ['select','constant','condition','autoGenerated']) assert.equal(copy[key],undefined);
    assert.equal(copy.functions.length,0);
    if(operator==='for-each-group') assert.equal(copy.groupBy,'');
  }
});
