import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Box, Cable, ChevronDown, ChevronRight, CirclePlay, FileJson, Folder, Globe, HardDrive, Plus, Save, Settings2, Terminal, Workflow} from 'lucide-react';
import './styles.css';

type Kind='start'|'http'|'file'|'transform'|'log'|'kafka'|'java'|'end';
type Node={id:string,type:Kind,name:string,position:{x:number,y:number},config:Record<string,any>}; type Edge={id:string,source:string,target:string,label?:string}; type Project={id:string,name:string,description:string,process:{id:string,name:string,activities:Node[],transitions:Edge[]}};
const palette: {type:Kind; label:string; icon:React.ReactNode}[]=[{type:'http',label:'HTTP / REST',icon:<Globe/>},{type:'file',label:'File / SFTP',icon:<HardDrive/>},{type:'transform',label:'Transform',icon:<FileJson/>},{type:'kafka',label:'Kafka Publish',icon:<Cable/>},{type:'java',label:'Java Activity',icon:<Box/>},{type:'log',label:'Log',icon:<Terminal/>}];
const sample:Project={id:'order-integration',name:'Order Integration',description:'Starter HTTP-to-file integration',process:{id:'main',name:'Main Process',activities:[{id:'start',type:'start',name:'Start',position:{x:80,y:190},config:{}},{id:'http1',type:'http',name:'Get Order',position:{x:280,y:190},config:{method:'GET',url:'https://api.example.com/orders/${input.orderId}',timeout:30}},{id:'map1',type:'transform',name:'Map Order',position:{x:490,y:190},config:{mappings:{orderId:'${input.orderId}'}}},{id:'file1',type:'file',name:'Write File',position:{x:700,y:190},config:{operation:'write',path:'C:/IntegrationFabric/out/order.json'}},{id:'end',type:'end',name:'End',position:{x:900,y:190},config:{}}],transitions:[{id:'a',source:'start',target:'http1'},{id:'b',source:'http1',target:'map1'},{id:'c',source:'map1',target:'file1'},{id:'d',source:'file1',target:'end'}]}};
const colors:Record<Kind,string>={start:'#29c777',http:'#48a8ff',file:'#ad7bff',transform:'#ffb53f',log:'#6c829b',kafka:'#ff6689',java:'#ee7d49',end:'#e75668'};
function App(){const [project,setProject]=useState<Project>(sample),[selected,setSelected]=useState<string>('http1'),[logs,setLogs]=useState<any[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/projects/order-integration').then(r=>r.ok?r.json():Promise.reject()).then(setProject).catch(()=>fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sample)}));},[]);
 const node=project.process.activities.find(n=>n.id===selected); const nodes=project.process.activities;
 const update=(changes:Partial<Node>)=>setProject(p=>({...p,process:{...p.process,activities:p.process.activities.map(n=>n.id===selected?{...n,...changes}:n)}}));
 const add=(type:Kind)=>{const id=`${type}-${Date.now()}`,n:Node={id,type,name:palette.find(p=>p.type===type)?.label||type,position:{x:290+(nodes.length%3)*170,y:320+Math.floor(nodes.length/3)*120},config:type==='http'?{method:'GET',url:'https://'}:type==='file'?{operation:'read',path:''}:{}}; setProject(p=>({...p,process:{...p.process,activities:[...p.process.activities,n]}}));setSelected(id)};
 const save=async()=>{await fetch(`/api/projects/${project.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(project)});setLogs([{level:'INFO',message:'Project saved.',time:new Date().toISOString()},...logs])};
 const run=async()=>{setBusy(true);const r=await fetch(`/api/projects/${project.id}/run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:{orderId:'10001'}})});const out=await r.json();setLogs(out.logs||[]);setBusy(false)};
 const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));
 return <div className="app"><header><div className="brand"><Workflow/> <span>INTEGRATION <b>FABRIC</b></span><small>STUDIO</small></div><div className="crumb">Projects <ChevronRight/> {project.name} <ChevronRight/> <b>{project.process.name}</b></div><div className="actions"><button onClick={save}><Save/> Save</button><button className="run" onClick={run} disabled={busy}><CirclePlay/> {busy?'Running…':'Run'}</button></div></header>
 <aside className="explorer"><div className="pane-title">PROJECT EXPLORER <Plus size={15}/></div><div className="tree"><div><ChevronDown/><Folder className="folder"/> <b>{project.name}</b></div><div className="indent"><ChevronDown/><Folder className="folder"/> Processes</div><div className="indent2 active"><Workflow/> {project.process.name}</div><div className="indent"><ChevronRight/><Folder className="folder"/> Resources</div><div className="indent"><ChevronRight/><Folder className="folder"/> Schemas</div></div><div className="palette"><div className="pane-title">ACTIVITY PALETTE</div>{palette.map(p=><button key={p.type} onClick={()=>add(p.type)}><span style={{color:colors[p.type]}}>{p.icon}</span>{p.label}<Plus size={14}/></button>)}</div></aside>
 <main><div className="canvas-toolbar"><span><Activity/> Process Designer</span><span className="zoom">− &nbsp; 100% &nbsp; +</span></div><div className="canvas"><svg className="wires">{project.process.transitions.map(e=>{const a=byId[e.source],b=byId[e.target];if(!a||!b)return null;return <path key={e.id} d={`M${a.position.x+140},${a.position.y+38} C${a.position.x+170},${a.position.y+38} ${b.position.x-30},${b.position.y+38} ${b.position.x},${b.position.y+38}`} />})}</svg>{nodes.map(n=><button key={n.id} className={'node '+(selected===n.id?'selected':'')} style={{left:n.position.x,top:n.position.y,borderColor:colors[n.type]}} onClick={()=>setSelected(n.id)}><span className="node-icon" style={{background:colors[n.type]}}>{n.type==='http'?<Globe/>:n.type==='file'?<HardDrive/>:n.type==='transform'?<FileJson/>:n.type==='kafka'?<Cable/>:n.type==='java'?<Box/>:n.type==='start'?<CirclePlay/>:n.type==='end'?<span>■</span>:<Terminal/>}</span><strong>{n.name}</strong><small>{n.type.toUpperCase()}</small></button>)}</div>
 <section className="config"><div className="tabs"><b><Settings2/> Configuration</b><span>Input</span><span>Output</span><span>Errors</span></div>{node?<Config node={node} update={update}/>:<div className="empty">Select an activity to configure it.</div>}</section>
 </main><aside className="monitor"><div className="pane-title">EXECUTION LOG</div><div className="run-state"><span></span> Local Runtime · 127.0.0.1:8787</div>{logs.length?logs.map((l,i)=><div className={'log '+l.level.toLowerCase()} key={i}><small>{l.level}</small><p>{l.message}</p></div>):<div className="empty">Run the process to see activity logs.</div>}</aside></div>}
function Config({node,update}:{node:Node,update:(x:Partial<Node>)=>void}){const cfg=node.config;const set=(key:string,value:any)=>update({config:{...cfg,[key]:value}});return <div className="config-body"><label>Display name<input value={node.name} onChange={e=>update({name:e.target.value})}/></label><label>Activity type<input value={node.type.toUpperCase()} disabled/></label>{node.type==='http'&&<><label>Method<select value={cfg.method||'GET'} onChange={e=>set('method',e.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select></label><label className="wide">URL<input value={cfg.url||''} placeholder="https://service/path" onChange={e=>set('url',e.target.value)}/></label><label>Timeout (seconds)<input type="number" value={cfg.timeout||30} onChange={e=>set('timeout',Number(e.target.value))}/></label></>}{node.type==='file'&&<><label>Operation<select value={cfg.operation||'read'} onChange={e=>set('operation',e.target.value)}><option>read</option><option>write</option></select></label><label className="wide">File path<input value={cfg.path||''} onChange={e=>set('path',e.target.value)}/></label></>}{node.type==='kafka'&&<><label>Bootstrap servers<input value={cfg.bootstrapServers||''} onChange={e=>set('bootstrapServers',e.target.value)}/></label><label>Topic<input value={cfg.topic||''} onChange={e=>set('topic',e.target.value)}/></label></>}{node.type==='java'&&<><label className="wide">Worker command<input value={cfg.command||''} placeholder="java -jar worker.jar" onChange={e=>set('command',e.target.value)}/></label><label>Class name<input value={cfg.className||''} onChange={e=>set('className',e.target.value)}/></label></>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
