type Field = {path:string; type?:string; repeating?:boolean};

/** Match relative schema paths, preserving source spelling and explicit user mappings. */
export function autoMapLoopChildren(fields:Field[], mappings:any[], target:string, expression:any, sources:any[], occurrenceId?:string):any[] {
  if (typeof expression !== 'string') return mappings;
  const path = expression.match(/^\$\{([^}]+)\}$/)?.[1];
  if (!path) return mappings;
  let root = '', source:any;
  const legacy = path.match(/^activities\.([^.]+)\.output(?:\.(.*))?$/);
  if (legacy) { source=sources.find(s=>s.activity.id===legacy[1]);root=legacy[2] || ''; }
  else {
    const [name,...parts]=path.split('.'); root=parts.join('.');
    source=sources.find(s=>name==='input' ? s.activity.type==='start' : name==='last' ? s.distance===1 : s.reference===name || s.activity.id===name);
  }
  if (!source) return mappings;
  const prefix=root ? `${root}.` : '';
  const candidates=new Map<string,any[]>();
  for (const field of source.fields) {
    if (!field.key.toLowerCase().startsWith(prefix.toLowerCase())) continue;
    const relative=field.key.slice(prefix.length), key=relative.toLowerCase();
    const matches=candidates.get(key)||[];matches.push({field,relative});candidates.set(key,matches);
  }
  if (!candidates.size) return mappings;
  const next=mappings.filter(rule=>!(rule.occurrenceId===occurrenceId && rule.autoGenerated && rule.target.startsWith(`${target}.`)));
  const existing=new Set(next.filter(rule=>rule.occurrenceId===occurrenceId).map(rule=>rule.target));
  const parents=new Set(fields.flatMap(field=>{const parts=field.path.split('.');return parts.slice(0,-1).map((_,i)=>parts.slice(0,i+1).join('.'));}));
  for (const field of fields) {
    if (!field.path.startsWith(`${target}.`) || existing.has(field.path)) continue;
    const matches=candidates.get(field.path.slice(target.length+1).toLowerCase());
    if (matches?.length!==1) continue;
    if (parents.has(field.path) && !field.repeating) continue;
    const source=`\${${path}.${matches[0].relative}}`;
    next.push({target:field.path,source,targetType:field.type||'any',occurrenceId,functions:[],enabled:true,autoGenerated:true,
      ...(parents.has(field.path) && field.repeating ? {operator:'for-each',select:source} : {})});
  }
  return next;
}

export function relativeLoopExpression(value:any, scope?:string):any {
  if (!scope || typeof value!=='string') return value;
  const root=scope.match(/^\$\{([^}]+)\}$/)?.[1], path=value.match(/^\$\{([^}]+)\}$/)?.[1];
  return root && path?.startsWith(`${root}.`) ? path.slice(root.length+1) : value;
}

export function expandLoopExpression(value:any, scope?:string, paths?:string[]):any {
  const root=scope?.match(/^\$\{([^}]+)\}$/)?.[1];
  // Only plain relative paths are expanded; literals, functions and explicit references are untouched.
  const path = root && typeof value==='string' ? `${root}.${value}` : '';
  return root && typeof value==='string' && /^[A-Za-z_@][\w.@-]*$/.test(value) && !['true','false','null'].includes(value)
    && (!paths || paths.includes(path)) ? `\${${path}}` : value;
}
