import React, {useEffect, useRef, useState} from 'react';
import './mediation-studio.css';

const examples = [
  {name:'Normalize orders', input: '{"orders":[{"id":"A-100","buyer":" Ana ","amount":"42.50","status":"N"}]}', collection:'orders', inputFormat:'json', rules:[{source:'id',target:'order.id',required:true},{source:'buyer',target:'customer.name',operation:'trim'},{source:'amount',target:'order.total',operation:'number'},{source:'status',target:'order.status',operation:'lookup',values:{N:'New',C:'Complete'}}]},
  {name:'CSV customer onboarding',input:'name,email,active\nAna,ANA@EXAMPLE.COM,true',collection:'$',inputFormat:'csv',rules:[{source:'name',target:'name'},{source:'email',target:'email',operation:'lowercase'},{source:'active',target:'enabled',operation:'boolean'}]},
  {name:'XML to business JSON',input:'<orders><order><id>A-100</id><quantity>2</quantity></order></orders>',collection:'orders.order',inputFormat:'xml',rules:[{source:'id',target:'orderId',required:true},{source:'quantity',target:'quantity',operation:'integer'}]}
];
export default function MediationStudio({config,setConfig,schemas=[]}:any) {
  const [fields,setFields]=useState<any[]>([]), [schemaError,setSchemaError]=useState('');
  useEffect(()=>{const controller=new AbortController();setFields([]);setSchemaError('');if(!config.targetSchemaText?.trim())return;
    fetch('/api/mediation/schema',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schema:config.targetSchemaText}),signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw Error(value.detail||'Invalid target schema');if(!controller.signal.aborted)setFields(value.fields);}).catch(e=>{if(!controller.signal.aborted)setSchemaError(e.message);});return ()=>controller.abort();
  },[config.targetSchemaText]);
  const [input,setInput]=useState(config.sampleInput || '{}'), [result,setResult]=useState<any>(null), [message,setMessage]=useState(''), [busy,setBusy]=useState(false);
  const revision=useRef(0), rules=config.rules||[], hasMappings=Object.keys(config.inputMappings||{}).some(key=>key.startsWith('targetValues.'));
  const [contextText,setContextText]=useState('{"activities":{}}');
  const change=(next:any)=>{revision.current++;setResult(null);setMessage('Changed — preview again.');setConfig(next);};
  const update=(i:number,next:any)=>change({rules:rules.map((r:any,j:number)=>i===j?{...r,...next}:r)});
  const preview=async()=>{const current=revision.current;setBusy(true);setResult(null);try{
    const payload=(config.inputFormat||'json')==='json'?JSON.parse(input):input;
    const response=await fetch('/api/mediation/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input:payload,config,context:JSON.parse(contextText)})});const value=await response.json();
    if(!response.ok)throw Error(value.detail||'Preview failed');if(current===revision.current){setResult(value);setMessage(`${value.records} records transformed with ${value.rules} rules. No connector actions executed.`);}
  }catch(e:any){if(current===revision.current)setMessage(e.message);}finally{setBusy(false);}};
  return <section className="mediation-studio"><header><b>Mediation</b></header>
    <details><summary>Preview context for Input-tab mappings</summary><textarea aria-label="Mediation preview context" value={contextText} onChange={e=>{setContextText(e.target.value);revision.current++;setResult(null);}}/></details>
    <section className="mediation-target"><h3>Target structure</h3>
      <label>Project target schema<select value={config.targetSchemaId||''} onChange={e=>{const schema=schemas.find((s:any)=>s.id===e.target.value);change({targetSchemaId:schema?.id||'',targetSchemaText:schema?.content||''});}}><option value="">Inline / uploaded schema</option>{schemas.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label>Upload target schema<input type="file" accept=".json,.xsd" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>500000){setSchemaError('Schema exceeds 500 KB');return;}change({targetSchemaId:'',targetSchemaText:await file.text()});e.target.value='';}}/></label>
      <label>JSON Schema or XSD<textarea value={config.targetSchemaText||''} onChange={e=>change({targetSchemaId:'',targetSchemaText:e.target.value})} placeholder={'{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}'} spellCheck={false}/></label>
      
      {schemaError&&<p role="alert">{schemaError}</p>}<div className="mediation-target-fields">{fields.map(field=>{const mapped=rules.some((r:any)=>r.target===field.path);return <button key={field.path} type="button" disabled={mapped||rules.length>=200||!field.path} style={{marginLeft:Math.min(field.path.split('.').length-1,6)*12}} onClick={()=>change({rules:[...rules,{source:'',target:field.path,operation:'copy',required:field.required}]})}><b>{field.path}</b> · {field.type}{field.required?' · required':''} · {mapped?'Mapped':'+ Map field'}</button>;})}</div>
    </section>
    <div className="mediation-examples">{examples.map(e=><button type="button" key={e.name} onClick={()=>{setInput(e.input);change({...e,outputFormat:'json',asArray:true,sampleInput:e.input});}}>Load example: {e.name}</button>)}</div>
    <div className="mediation-options">{['inputFormat','outputFormat'].map(key=><label key={key}>{key==='inputFormat'?'Read as':'Write as'}<select value={config[key]||'json'} onChange={e=>change({[key]:e.target.value})}>{['json','xml','csv'].map(f=><option key={f}>{f}</option>)}</select></label>)}<label>Source collection<input value={config.collection??'$'} onChange={e=>change({collection:e.target.value})}/></label><label>Always return collection<input type="checkbox" checked={!!config.asArray} onChange={e=>change({asArray:e.target.checked})}/></label>{config.outputFormat==='xml'&&<label>XML root<input value={config.rootName||'message'} onChange={e=>change({rootName:e.target.value})}/></label>}</div>
    
    <div className="mediation-rules">{rules.map((r:any,i:number)=><article key={i}><b>{i+1}</b>{['source','target'].map(key=><label key={key}>{key==='source'?'Read field':'Business field'}<input aria-label={`Rule ${i+1} ${key}`} value={r[key]||''} onChange={e=>update(i,{[key]:e.target.value})}/></label>)}<label>Action<select value={r.operation||'copy'} onChange={e=>update(i,{operation:e.target.value})}>{['copy','trim','uppercase','lowercase','number','integer','boolean','lookup'].map(op=><option key={op}>{op}</option>)}</select></label><label>Required<input type="checkbox" checked={!!r.required} onChange={e=>update(i,{required:e.target.checked})}/></label><button type="button" aria-label={`Remove rule ${i+1}`} onClick={()=>change({rules:rules.filter((_:any,j:number)=>i!==j)})}>Remove</button><details><summary>Defaults, constants and lookup</summary>{['default','constant',...(r.operation==='lookup'?['values']:[])].map(key=><label key={`${key}-${JSON.stringify(r[key])}`}>{key}<input defaultValue={r[key]===undefined?'':JSON.stringify(r[key])} onBlur={e=>{try{const next={...r};if(!e.target.value.trim())delete next[key];else next[key]=JSON.parse(e.target.value);change({rules:rules.map((v:any,j:number)=>i===j?next:v)});}catch{setMessage(`${key}: invalid JSON; value was not saved.`);}}}/></label>)}</details></article>)}</div>
    <button type="button" disabled={rules.length>=200} onClick={()=>change({rules:[...rules,{source:'$',target:'',operation:'copy'}]})}>+ Add business field</button>
    <div className="mediation-preview"><label>Example input · preview only<textarea spellCheck={false} value={input} onChange={e=>{setInput(e.target.value);change({sampleInput:e.target.value});}}/></label><label>Result<pre>{result?typeof result.output==='string'?result.output:JSON.stringify(result.output,null,2):'Preview the recipe to see your business message.'}</pre></label></div><button type="button" disabled={busy||(!rules.length&&!hasMappings)} onClick={preview}>{busy?'Testing…':'Preview mediation'}</button><p role="status">{message}</p>
    {result&&<details open><summary>Explain this transformation</summary><ol>{result.trace.map((r:any,i:number)=><li key={i}>Read <code>{r.source}</code> → {r.operation} → write <code>{r.target}</code></li>)}</ol></details>}
    </section>;
}
