import React,{useMemo,useState}from'react';
import{Braces,CheckCircle2,CodeXml,FileJson,Plus,Sparkles,Trash2,X}from'lucide-react';

export type SchemaDoc={id:string;name:string;content:string};
type Field={id:string;name:string;type:string;min:string;max:string};
const header=`<?xml version="1.0" encoding="UTF-8"?>\n<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">`;
const footer=`</xs:schema>`;
const escapeXml=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const infer=(value:any)=>value===null?'xs:string':typeof value==='boolean'?'xs:boolean':typeof value==='number'?(Number.isInteger(value)?'xs:integer':'xs:decimal'):'xs:string';
function fieldsToXsd(root:string,fields:Field[]){return`${header}\n  <xs:element name="${escapeXml(root||'root')}">\n    <xs:complexType>\n      <xs:sequence>\n${fields.map(f=>`        <xs:element name="${escapeXml(f.name||'field')}" type="${f.type}" minOccurs="${f.min}" maxOccurs="${f.max}"/>`).join('\n')}\n      </xs:sequence>\n    </xs:complexType>\n  </xs:element>\n${footer}`}
function jsonElement(name:string,value:any,depth=2):string{const p='  '.repeat(depth);if(Array.isArray(value)){const item=value[0]??'';return`${p}<xs:element name="${escapeXml(name)}" minOccurs="0" maxOccurs="unbounded">\n${jsonBody(item,depth+1)}\n${p}</xs:element>`}if(value&&typeof value==='object')return`${p}<xs:element name="${escapeXml(name)}">\n${jsonBody(value,depth+1)}\n${p}</xs:element>`;return`${p}<xs:element name="${escapeXml(name)}" type="${infer(value)}" minOccurs="0"/>`}
function jsonBody(value:any,depth:number):string{const p='  '.repeat(depth);if(value&&typeof value==='object'&&!Array.isArray(value))return`${p}<xs:complexType>\n${p}  <xs:sequence>\n${Object.entries(value).map(([k,v])=>jsonElement(k,v,depth+2)).join('\n')}\n${p}  </xs:sequence>\n${p}</xs:complexType>`;return`${p}<xs:simpleType><xs:restriction base="${infer(value)}"/></xs:simpleType>`}
export function jsonToXsd(text:string){const data=JSON.parse(text),root=Array.isArray(data)?'root':Object.keys(data).length===1?Object.keys(data)[0]:'root',value=root==='root'?data:data[root];return`${header}\n${jsonElement(root,value,1)}\n${footer}`}
function xmlNode(node:Element,depth=2):string{const p='  '.repeat(depth),children=[...node.children];if(!children.length)return`${p}<xs:element name="${escapeXml(node.tagName)}" type="${infer(node.textContent?.trim()||'')}" minOccurs="0"/>`;return`${p}<xs:element name="${escapeXml(node.tagName)}">\n${p}  <xs:complexType>\n${p}    <xs:sequence>\n${children.map(c=>xmlNode(c,depth+3)).join('\n')}\n${p}    </xs:sequence>\n${p}  </xs:complexType>\n${p}</xs:element>`}
export function xmlToXsd(text:string){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror')||!doc.documentElement)throw new Error('The XML sample is not well formed.');return`${header}\n${xmlNode(doc.documentElement,1)}\n${footer}`}
export function validateXsd(content:string){const doc=new DOMParser().parseFromString(content,'application/xml');if(doc.querySelector('parsererror'))return'XSD is not well-formed XML.';const root=doc.documentElement;if(!/schema$/i.test(root.localName))return'Root element must be xs:schema.';if(root.namespaceURI!=='http://www.w3.org/2001/XMLSchema')return'XML Schema namespace is missing or incorrect.';if(!root.querySelector('element'))return'Add at least one xs:element declaration.';return''}

const suggestions=['<xs:element name="" type="xs:string"/>','<xs:complexType>','<xs:sequence>','<xs:choice>','<xs:attribute name="" type="xs:string"/>','minOccurs="0"','maxOccurs="unbounded"','type="xs:boolean"','type="xs:dateTime"'];
export default function SchemaStudio({schema,initialTab='design',onClose,onSave}:{schema?:SchemaDoc;initialTab?:'design'|'source'|'xml'|'json';onClose:()=>void;onSave:(s:SchemaDoc)=>void}){const[tab,setTab]=useState(initialTab),[name,setName]=useState(schema?.name||'NewSchema.xsd'),[root,setRoot]=useState('root'),[fields,setFields]=useState<Field[]>([{id:'1',name:'id',type:'xs:string',min:'1',max:'1'}]),[source,setSource]=useState(schema?.content||fieldsToXsd('root',[{id:'1',name:'id',type:'xs:string',min:'1',max:'1'}])),[sample,setSample]=useState(''),[message,setMessage]=useState('');const filtered=useMemo(()=>suggestions.filter(x=>x.toLowerCase().includes((source.match(/[\w:"=-]+$/)?.[0]||'').toLowerCase())).slice(0,6),[source]);
 const activate=(next:typeof tab)=>{if(tab==='design')setSource(fieldsToXsd(root,fields));setTab(next);setMessage('')},generate=(kind:'xml'|'json')=>{try{const x=kind==='xml'?xmlToXsd(sample):jsonToXsd(sample);setSource(x);setTab('source');setMessage('Schema generated successfully. Review and save it.')}catch(e:any){setMessage(e.message)}},validate=()=>{const error=validateXsd(tab==='design'?fieldsToXsd(root,fields):source);setMessage(error||'Schema is well formed and contains an XSD element declaration.')},save=()=>{const content=tab==='design'?fieldsToXsd(root,fields):source,error=validateXsd(content);if(error){setMessage(error);return}onSave({id:schema?.id||`schema-${Date.now()}`,name:name.toLowerCase().endsWith('.xsd')?name:`${name}.xsd`,content})};
 return <div className="schema-backdrop"><div className="schema-studio"><header><div><CodeXml/><b>XSD Schema Studio</b><small>{schema?'Edit existing schema':'Create a reusable XML schema'}</small></div><label>Schema file<input value={name} onChange={e=>setName(e.target.value)}/></label><button title="Close" onClick={onClose}><X/></button></header><nav>{([['design','Visual Designer'],['source','XSD Source'],['xml','From XML Sample'],['json','From JSON Sample']]as const).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>activate(id)} key={id}>{id==='design'?<Braces/>:id==='source'?<CodeXml/>:id==='xml'?<Sparkles/>:<FileJson/>}{label}</button>)}</nav><main>
 {tab==='design'&&<div className="schema-design"><aside><b>Schema outline</b><div><CodeXml/> xs:schema</div><div className="schema-indent"><Braces/> {root||'root'}</div>{fields.map(f=><div className="schema-indent2" key={f.id}>◇ {f.name||'field'}</div>)}</aside><section><div className="schema-section-title"><div><b>Visual element designer</b><small>Define the root and child sequence without writing XSD.</small></div><button onClick={()=>setFields(x=>[...x,{id:String(Date.now()),name:'field',type:'xs:string',min:'0',max:'1'}])}><Plus/> Add element</button></div><label>Root element name<input value={root} onChange={e=>setRoot(e.target.value)}/></label><div className="schema-grid heading"><b>Element name</b><b>Data type</b><b>Min</b><b>Max</b><span/></div>{fields.map((f,i)=><div className="schema-grid" key={f.id}><input value={f.name} onChange={e=>setFields(x=>x.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/><select value={f.type} onChange={e=>setFields(x=>x.map((v,j)=>j===i?{...v,type:e.target.value}:v))}>{['xs:string','xs:boolean','xs:integer','xs:decimal','xs:date','xs:dateTime','xs:anyURI'].map(t=><option key={t}>{t}</option>)}</select><input value={f.min} onChange={e=>setFields(x=>x.map((v,j)=>j===i?{...v,min:e.target.value}:v))}/><input value={f.max} onChange={e=>setFields(x=>x.map((v,j)=>j===i?{...v,max:e.target.value}:v))}/><button onClick={()=>setFields(x=>x.filter((_,j)=>j!==i))}><Trash2/></button></div>)}</section></div>}
 {tab==='source'&&<div className="schema-source"><div className="editor-title"><b>Interactive XSD source editor</b><small>Suggestions update as you type. Click one to insert it.</small></div><div className="code-shell"><div className="line-rail">{source.split('\n').map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea spellCheck={false} value={source} onChange={e=>setSource(e.target.value)}/></div><div className="schema-suggestions"><b>Dynamic suggestions</b>{filtered.map(s=><button key={s} onClick={()=>setSource(x=>`${x}${x.endsWith('\n')?'':'\n'}  ${s}`)}><code>{s}</code></button>)}</div></div>}
 {tab==='xml'&&<Sample title="Generate XSD from sample XML" placeholder={'<customer>\n  <id>1001</id>\n  <active>true</active>\n</customer>'} value={sample} setValue={setSample} onGenerate={()=>generate('xml')}/>} 
 {tab==='json'&&<Sample title="Generate XSD from sample JSON" placeholder={'{\n  "customer": {\n    "id": 1001,\n    "active": true\n  }\n}'} value={sample} setValue={setSample} onGenerate={()=>generate('json')}/>} 
 </main><footer><span className={message&&/well formed|successfully/.test(message)?'ok':'notice'}>{message&&<><CheckCircle2/>{message}</>}</span><button onClick={validate}>Validate</button><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save schema</button></footer></div></div>}
function Sample({title,placeholder,value,setValue,onGenerate}:{title:string;placeholder:string;value:string;setValue:(v:string)=>void;onGenerate:()=>void}){return <div className="schema-sample"><div><b>{title}</b><p>Paste a representative payload. The generator infers elements, complex types, arrays, occurrence rules, and primitive XSD data types.</p><ul><li>Use a complete, well-formed sample.</li><li>Review inferred optionality and numeric types.</li><li>The generated XSD opens in the source editor.</li></ul></div><section><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} spellCheck={false}/><button onClick={onGenerate}><Sparkles/> Generate XSD</button></section></div>}
